services:
  web:
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx/:ro
    ports:
      - "8863:80"
      - "8862:8862"
    environment:
      - NGINX_PORT=80
    command: [ nginx-debug, '-g', 'daemon off;' ]
    restart: always
