/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BilibiliBanner: typeof import('./components/bilibiliBanner/Index.vue')['default']
    CategoryAnchor: typeof import('./components/CategoryAnchor.vue')['default']
    CategoryNav: typeof import('./components/categoryNav.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    GlowCard: typeof import('./components/GlowCard.vue')['default']
    HistoryBannerAnimateBanner: typeof import('./components/historyBanner/AnimateBanner.vue')['default']
    HistoryBannerBanner_20240527: typeof import('./components/historyBanner/Banner_20240527.vue')['default']
    IEpBack: typeof import('~icons/ep/back')['default']
    IEpBottom: typeof import('~icons/ep/bottom')['default']
    IEpCirclePlusFilled: typeof import('~icons/ep/circle-plus-filled')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    Layout: typeof import('./components/layout/Index.vue')['default']
    LayoutAside: typeof import('./components/layout/Aside.vue')['default']
    LayoutFooter: typeof import('./components/layout/Footer.vue')['default']
    LayoutHeader: typeof import('./components/layout/Header.vue')['default']
    LoadPage: typeof import('./components/LoadPage.vue')['default']
    LocalSearch: typeof import('./components/LocalSearch.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Twikoo: typeof import('./components/Twikoo.vue')['default']
  }
}
