/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimateBanner: typeof import('./components/historyBanner/AnimateBanner.vue')['default']
    Aside: typeof import('./components/layout/Aside.vue')['default']
    Banner_20240527: typeof import('./components/historyBanner/Banner_20240527.vue')['default']
    BilibiliBanner: typeof import('./components/bilibiliBanner/Index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    GlowCard: typeof import('./components/GlowCard.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    HistoryBannerAnimateBanner: typeof import('./components/historyBanner/AnimateBanner.vue')['default']
    HistoryBannerBanner_20240527: typeof import('./components/historyBanner/Banner_20240527.vue')['default']
    IEpBack: typeof import('~icons/ep/back')['default']
    IEpBottom: typeof import('~icons/ep/bottom')['default']
    IEpCaretBottom: typeof import('~icons/ep/caret-bottom')['default']
    IEpCirclePlusFilled: typeof import('~icons/ep/circle-plus-filled')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpRemoveFilled: typeof import('~icons/ep/remove-filled')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    Layout: typeof import('./components/layout/Index.vue')['default']
    LayoutAside: typeof import('./components/layout/Aside.vue')['default']
    LayoutFooter: typeof import('./components/layout/Footer.vue')['default']
    LayoutHeader: typeof import('./components/layout/Header.vue')['default']
    LocalSearch: typeof import('./components/LocalSearch.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
